stages:
- build
- deploy

variables:
  DOCKER_REGISTRY: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
  DOCKER_IMAGE: ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  image: docker:20.10.16
  services:
  - docker:20.10.16-dind
  before_script:
  # Debugging outputs to verify variables
  - echo " AWS_REGION:"
  - echo ${AWS_REGION}
  - echo "AWS_ACCOUNT_ID:"
  - echo ${AWS_ACCOUNT_ID}
  - apk add --no-cache curl jq python3 py3-pip
  # Install necessary tools
  - pip install awscli
  # Configure AWS CLI
  - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
  - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
  - aws configure set region ${AWS_REGION}
  # Docker login to AWS ECR
  - aws ecr get-login-password --region ${AWS_REGION} | docker login --username
    AWS --password-stdin ${DOCKER_REGISTRY}
  script:
  - docker build -t ${DOCKER_IMAGE} .
  - docker push ${DOCKER_IMAGE}

deploy:
  stage: deploy
  image:
    name: amazon/aws-sam-cli-build-image-python3.8
    entrypoint: [ "" ]
  before_script:
  - export DOCKER_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
  - export
    DOCKER_IMAGE=${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}
  - pip install awscli
  # Install AWS CLI
  # Configure AWS CLI
  - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
  - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
  - aws configure set region ${AWS_REGION}
  # Get VPC ID and subnet IDs from the default VPC
  - |
    export VPC_ID=$(aws ec2 describe-vpcs --filters "Name=isDefault,Values=true" --query "Vpcs[0].VpcId" --output text)
    SUBNET_IDS=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" --query "Subnets[*].SubnetId" --output text)
    SUBNET_ARRAY=($SUBNET_IDS)
    export SUBNET1=${SUBNET_ARRAY[0]}
    export SUBNET2=${SUBNET_ARRAY[1]}
  script:
  - echo "Deploying with DockerImageUri:" # Debug output
  - echo ${DOCKER_IMAGE}
  - sam build -t ec2-template.yaml
  - |
    sam deploy --stack-name recipeapp-stack \
    --template-file .aws-sam/build/template.yaml \
    --capabilities CAPABILITY_IAM \
    --no-confirm-changeset \
    --no-fail-on-empty-changeset \
    --parameter-overrides \
    DockerImageUri=${DOCKER_IMAGE} \
    Subnet1=${SUBNET1} \
    Subnet2=${SUBNET2} \
    VpcId=${VPC_ID}
  only:
  - prod
