"""Convert ingredients and procedure to arrays with server default

Revision ID: 1db94084b214
Revises: e1dbee9e842e
Create Date: 2024-11-06 02:24:43.961085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1db94084b214'
down_revision = 'e1dbee9e842e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE recipes 
        ALTER COLUMN ingredients TYPE varchar[] 
        USING string_to_array(ingredients, E'\n'),
        ALTER COLUMN ingredients SET DEFAULT ARRAY[]::varchar[];
        
        ALTER TABLE recipes 
        ALTER COLUMN procedure TYPE varchar[] 
        USING string_to_array(procedure, E'\n'),
        ALTER COLUMN procedure SET DEFAULT ARRAY[]::varchar[];
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE recipes 
        ALTER COLUMN ingredients TYPE text 
        USING array_to_string(ingredients, E'\n'),
        ALTER COLUMN ingredients SET DEFAULT '';
        
        ALTER TABLE recipes 
        ALTER COLUMN procedure TYPE text 
        USING array_to_string(procedure, E'\n'),
        ALTER COLUMN procedure SET DEFAULT '';
    """)
    # ### end Alembic commands ###
